[package]
name = "rust-grpc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.9.2"
tokio = { version = "1.0.1", features = ["macros", "rt-multi-thread"] }
prost = "0.11"

[build-dependencies]
tonic-build = "0.9.2"